Improves Appraisal tests
RockefellerArchiveCenter/aurora pull request #469
Opened 2021-06-28 18:12 UTC by helrond

Adds coverage for some logic branches, uses fixtures and reduces repetitive code.

**NOTE this is branched from #467 so that should be merged first**

Fixes #458

2021-06-28 19:50 UTC, bonniegee requested changes
While the methods added to the AccessionCreateView generally make sense, I think docstrings would be useful.

2021-06-29 13:25 UTC, p-galligan reviewed
Just one question before approving:

Why are you commenting out code in `test_bagitprofiles.py` and `test_rights.py` instead of deleting?

2021-06-29 13:30 UTC, bonniegee approved these changes

2021-06-29 13:41 UTC, helrond commented
@p-galligan I'm going to replace those tests as I go, but I still wanted to know what they were. I think both of these tests include hard-coded data which is clashing with data added to the database in earlier tests. Converting `TestCase` to `TransactionTestCase` and using fixtures is a much terser way of producing consistent database state.

2021-06-29 13:43 UTC, p-galligan approved these changes

2021-06-29 15:12 UTC, HaSistrunk approved these changes

2021-06-30 18:08 UTC, merged