Replace Google with Matomo Tag Manager for Analytics
RockefellerArchiveCenter/aurora pull request #580
Opened 2022-10-14 18:57 UTC by HaSistrunk

Fixes #579 

Replaces Google Tag Manager implementation with Matomo Tag Manager tracking. Includes replacement of tracking id variable in Travis for deployment.

2022-10-31 14:53 UTC, daremiyo requested changes
The Google Tag Manager ID in the config.py.deploy file also needs to be replaced with a Matomo ID

2022-10-31 17:45 UTC, daremiyo approved these changes

2022-10-31 23:04 UTC, katleonard approved these changes

2022-11-04 13:37 UTC, EcZX approved these changes

2022-11-07 20:14 UTC, merged